# Generated by Django 4.1.3 on 2022-12-05 09:18

import customer.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', customer.managers.CustomUserManager()),
            ],
        ),
    ]
